---
- name: "Create Jenkins Group"
  failed_when: false
  ansible.builtin.group:
    name: "{{ install_jenkins__group }}"
    state: present
    gid: 1000

- name: "Edit the Jenkins user"
  failed_when: false
  ansible.builtin.user:
    name: "{{ install_jenkins__user }}"
    groups: "docker,{{ install_jenkins__group }}"
    state: present
    create_home: false
    shell: "/sbin/nologin"
    uid: 1000

- name: "Check if folder home exist"
  register: folder_check
  ansible.builtin.stat:
    path: "{{ install_jenkins__home }}"

- name: "Create home path"
  when: not folder_check.stat.exists
  ansible.builtin.file:
    path: "{{ install_jenkins__home }}"
    state: directory
    recurse: yes
    mode: "0700"
    group: "{{ install_jenkins__group }}"
    owner: "{{ install_jenkins__user }}"

- name: "Install Jenkins with Docker"
  community.docker.docker_container:
    name: "{{ install_jenkins__container_name }}"
    image: "jenkins/jenkins"
    state: "started"
    recreate: false
    restart_policy: "always"
    ports:
      - "{{ install_jenkins__host }}:{{ install_jenkins__port }}:8080"
      - "0.0.0.0:{{ install_jenkins__client_port }}:50000"
    volumes:
      - "{{ install_jenkins__home }}:/var/jenkins_home"
    env:
      JAVA_OPTS: "-Xmx{{ install_jenkins__heap }}"
