---
- name: "Converge"
  hosts: "cicd-docker-dind"
  tasks:

    - name: "Include labocbz.install_jenkins"
      tags:
        - "labocbz.install_jenkins"
      vars:
        install_jenkins__user: "{{ inv_install_jenkins__user }}"
        install_jenkins__group: "{{ inv_install_jenkins__group }}"
        install_jenkins__home: "{{ inv_install_jenkins__home }}"
        install_jenkins__container_name: "{{ inv_install_jenkins__container_name }}"
        install_jenkins__host: "{{ inv_install_jenkins__host }}"
        install_jenkins__port: "{{ inv_install_jenkins__port }}"
        install_jenkins__client_port: "{{ inv_install_jenkins__client_port }}"
      ansible.builtin.include_role:
        name: "labocbz.install_jenkins"
